[WIP] Enable session manager and ssh by adding ssh public keys
cloudposse/terraform-aws-dynamic-subnets pull request #141
Opened 2021-09-22 07:00 UTC by drselump14

## what
* Enable session manager for the created nat instance. Need a proper IAM policy for users
* Enable ssh to nat instance by adding ssh public keys

## why
* Enable session manager/ssh to nat instance make it more useful because we  can use it as bastion server

## references
* https://github.com/cloudposse/terraform-aws-dynamic-subnets/issues/73

2021-09-22 11:22 UTC, drselump14 commented on iam.tf
> +data "aws_iam_policy_document" "main" {
This one is an intended setting. Any idea how to exclude this from cloudsplaining?

2021-11-13 17:34 UTC, nitrocode commented on variables.tf
> +}
I don't think we should be allowing manual ssh keys as an input.

You could expose user_data instead and pass in the keys manually if you like, but this is unnecessary if ssm access is enabled

```suggestion
variable "nat_instance_public_ssh_keys" {
  type        = list(string)
  description = "SSH public keys that we want to attach to the nat instance"
  default     = []
}
```

2021-11-13 17:35 UTC, nitrocode commented on nat-instance.tf
> +
If this is desired, this can be attached outside of this module. I don't think we should allow ssh when we have ssm.

```suggestion
```

2021-11-13 17:36 UTC, nitrocode commented on iam.tf
> +  count = module.this.enabled && local.create_nat_instance_profile ? 1 : 0
```suggestion
  count = local.enabled && local.create_nat_instance_profile ? 1 : 0
```

2021-11-13 17:37 UTC, nitrocode commented on iam.tf
> +  count = module.this.enabled && local.create_nat_instance_profile ? 1 : 0
```suggestion
  count = local.enabled && local.create_nat_instance_profile ? 1 : 0
```

2021-11-13 17:37 UTC, nitrocode commented on iam.tf
> +  count  = module.this.enabled && local.create_nat_instance_profile ? 1 : 0
```suggestion
  count  = local.enabled && local.create_nat_instance_profile ? 1 : 0
```

2021-11-13 17:37 UTC, nitrocode commented on iam.tf
> +  statement {
```suggestion
  count = local.enabled && local.create_nat_instance_profile ? 1 : 0

  statement {
```

2021-11-13 17:38 UTC, nitrocode commented on iam.tf
> +  policy = data.aws_iam_policy_document.main.json
```suggestion
  policy = join("", data.aws_iam_policy_document.main.*.json)
```

2021-11-13 17:39 UTC, nitrocode commented on iam.tf
> +  assume_role_policy = data.aws_iam_policy_document.default.json
```suggestion
  assume_role_policy = join("", data.aws_iam_policy_document.default.*.json)
```

2021-11-13 17:39 UTC, nitrocode commented on iam.tf
> +  statement {
```suggestion
  count = local.enabled && local.create_nat_instance_profile ? 1 : 0

  statement {
```

2022-05-12 01:20 UTC, Nuru requested changes
With v2 of this module, you can suppress the NAT Instance creation, create your own NAT instances however you like, and add routes to them, so this PR is not strictly needed anymore. 

If you want to implement these features, it should be via a launch template, so you can specify SSH keys by name. However, NAT Instances [are deprecated](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_NAT_Instance.html) and do not support NAT64. I am therefore not inclined to add additional support for them.

2022-05-13 23:56 UTC, Nuru commented
For better NAT instance support, you can use an alternate module such as https://github.com/int128/terraform-aws-nat-instance (we have not vetted it, just noticed it) to create NAT instances and easily connect them to the private subnets. 

```hcl
module "dynamic_subnets" {
  source  = "cloudposse/dynamic-subnets/aws"
  version = "2.0.0"

  nat_gateway_enabled  = false
  nat_instance_enabled = false
  # etc . . .
}

resource "aws_route" "private" {
  count = length(module.dynamic_subnets.private_route_table_ids)

  route_table_id         = module.dynamic_subnets.private_route_table_ids[count.index]
  destination_cidr_block = "0.0.0.0/0"
  network_interface_id   = element(local.nat_instances.*.primary_network_interface_id, count.index)
}
```

We are not going to invest additional resources on NAT Instance support in this module at this time. We recommend using NAT Gatways instead, and if you want to save money, use a single NAT Gateway rather than one per region.

2022-05-13 23:56 UTC, closed without merging